name: mw-env
channels:
  - anaconda
  - conda-forge
  - jeremyschlatter
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.7.1
  - appdirs=1.4.3
  - attrs=19.1.0
  - black=19.3b0
  - blas=1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - click=7.0
  - cycler=0.10.0
  - dbus=1.13.6
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=58.2
  - intel-openmp=2019.4
  - jpeg=9c
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - ncurses=6.1
  - openssl=1.1.1d
  - pcre=8.41
  - pip=19.1.1
  - pthread-stubs=0.4
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.2
  - qt=5.9.7
  - readline=7.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - tk=8.6.8
  - toml=0.10.0
  - tornado=6.0.3
  - wheel=0.33.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - boto3==1.10.45
    - botocore==1.13.45
    - cloudpickle==1.2.2
    - colorama==0.4.3
    - docutils==0.15.2
    - filelock==3.0.12
    - funcsigs==1.0.2
    - importlib-metadata==1.3.0
    - jmespath==0.9.4
    - jsonschema==3.2.0
    - more-itertools==8.0.2
    - numpy==1.18.0
    - packaging==19.2
    - pluggy==0.13.1
    - protobuf==3.11.2
    - psutil==5.6.7
    - py==1.8.0
    - py-spy==0.3.1
    - pyrsistent==0.15.6
    - pytest==5.3.2
    - pyyaml==5.2
    - ray==0.8.0
    - redis==3.3.11
    - s3transfer==0.2.1
    - scipy==1.4.1
    - setproctitle==1.1.10
    - urllib3==1.25.7
    - wcwidth==0.1.7
    - zipp==0.6.0

